# Jekyll Configuration for GitHub Pages
title: "Jiarun Liu | Academic Portfolio"
description: "Modern Academic Portfolio - CV, Code Demos, Gallery"
url: "https://klgr123.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - venv/
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - .DS_Store

# Include specific files/directories
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# SEO settings
author: Jiarun Liu 刘嘉润
locale: en_US

# GitHub Pages settings
repository: KLGR123/KLGR123.github.io 